apiVersion: v1
kind: Service
metadata:
  name: gwservice
  labels:
    app: readiness
spec:
  selector:
    app: readiness
  ports:
  - port: 8086
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer